### ISSUE TITLE
Support scalar and array for component parameters

### ISSUE THREAD

**Issue by ThibHlln** [hydro-jules/cm4twc#21]
At the moment a `Component` expects its parameters to be scalar values, i.e. they are the same everywhere in the `SpaceDomain` (and also constant over time).

Since there is no type checking on the parameters, only their availability, an array can be provided for the parameters. However, this is problematic in several ways:
- parameter values are stored in the yaml config file, so this is not the best way to store a data array
- if the component is not purely implemented in Python (e.g. Fortran/C library), the dimensions of the paramater must be known, or at least the rank of the array in Fortran

So there needs to be a way to deal with these two problems. 

For the first one, if the parameter is given as an array, a NC file could be written (if parameter value does not come from one already), and the yaml file should point to this file. The scalar case should probably still be supported in the way it is at the moment, as writing a NC file for one scalar is probably not optimal.

For the second one, not sure how to deal with it yet. Converting scalars to arrays could be a solution, so that a component would also get arrays.

**Comment by ThibHlln** [comment]
In terms of the API, I think we should support `cf.Data` and `cf.Field` as parameter values.  This would allow us to add checks on the parameter units.

If parameters are scalars, it is more straightforward to create a Data object than a Field:
```python
parameters = {
    'paramater_a': cf.Data(10, 'm2'),
    'parameter_b': cf.Data(120, 's')
}
```

If parameters are arrays, they need to be provided metadata (at least for spatial context), so a Data object would not be enough, and a Field would be required - it will most likely be stored in a file (if not, the framework would store it in a file in *config_directory*):
```python
parameters = {
    'paramater_a': cf.read('my_file.nc').select_field('long_name='parameter_a'),
    'parameter_b': cf.read('my_file.nc').select_field('long_name='parameter_b'),
}
```

In terms of the YAML configuration file, the former could be stored as follows:
```YAML
parameters:
  parameter_a:
    value: 10
    units: m2
  parameter_b:
    value: 120
    units: s
```

While the latter could be stored as follows:
```YAML
parameters:
  parameter_a:
    files: my_file.nc
    select: paramater_a
  parameter_b:
    files: my_file.nc
    select: paramater_b
```
